name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install selenium webdriver-manager

    - name: Install Apache & PHP
      run: sudo apt update && sudo apt install apache2 php libapache2-mod-php php-mysql -y

    - name: Move files to Apache root
      run: |
        sudo rm -rf /var/www/html/*
        sudo cp -r * /var/www/html/
        sudo chown -R www-data:www-data /var/www/html/
        sudo systemctl restart apache2

    - name: Check if Apache is running
      run: sudo systemctl status apache2

    - name: Wait for Apache to start
      run: sleep 10

    - name: Verify server response
      run: curl -I http://localhost || exit 1

    - name: Run Selenium Tests
      run: python test2.py
