name: Automated Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: damncrud
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for MySQL to be ready
        run: sleep 20

      - name: Import database
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -P 3306 -u root -proot damncrud < db/damncrud.sql

      - name: Set up PHP and start server
        run: |
          sudo apt-get install -y php php-mysqli
          php -S localhost:8000 -t . &

      - name: Install dependencies for Selenium
        run: |
          sudo apt-get install -y firefox
          pip install selenium

      - name: Run Selenium tests
        run: python selenium_test.py
