name: Selenium Test Automation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  selenium-test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Selenium Tests (test2.py)
        env:
          DISPLAY: :99
        run: |
          python test2.py
