name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: damncrud

      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest pytest-xdist

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h "127.0.0.1" --silent; do
          echo 'waiting for mysql to be ready...'
          sleep 5
        done

    - name: Set up database
      run: |
        mysql -h 127.0.0.1 -u root -proot damncrud < db/schema.sql
        mysql -h 127.0.0.1 -u root -proot damncrud < db/data.sql

    - name: Run Selenium tests
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: |
        pytest -n auto --maxfail=1 --disable-warnings c:/xampp/htdocs/DamnCRUD-main
