name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-firefox:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytest pytest-xdist

    - name: Run Selenium tests
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: |
        pytest -n auto c:/xampp/htdocs/DamnCRUD-main/test.py c:/xampp/htdocs/DamnCRUD-main/test2.py
